'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const artifact = path.resolve(process.argv[2]);
  const report = JSON.parse(fs.readFileSync(path.join(path.dirname(artifact),'report.json'),'utf8'));
  const browser = await chromium.launch({headless:true});
  try {
    const context = await browser.newContext({offline:true,viewport:{width:1280,height:900},serviceWorkers:'block'});
    const attemptedNetwork = [], errors = [], consoleErrors = [];
    await context.route('**/*', async route => {
      if (route.request().url().startsWith('file:')) return route.continue();
      attemptedNetwork.push(route.request().url());
      await route.abort();
    });
    const page = await context.newPage();
    page.on('pageerror',e => errors.push(String(e)));
    page.on('console',m => {if(m.type()==='error')consoleErrors.push(m.text());});
    page.on('request',r => {if (/^https?:/.test(r.url()))attemptedNetwork.push(r.url());});
    await page.goto(pathToFileURL(artifact).href);
    await page.waitForFunction(() => document.querySelector('#summary').textContent.length>0);
    assert.equal(await page.locator('#analysis-label').isVisible(),false);
    assert.match(await page.locator('#rows').innerText(),/Baseline selected/);
    assert.equal(await page.locator('#previous').isDisabled(),true);
    await page.locator('#view').selectOption('snapshot');
    assert.equal(await page.locator('#rows details').count(),6);
    await page.locator('#ecosystem').selectOption('python');
    assert.equal(await page.locator('#rows details').count(),3);
    await page.locator('#category').selectOption('build-system.requires');
    assert.equal(await page.locator('#rows details').count(),1);
    await page.locator('#reset').click();
    await page.locator('#search').fill('workspace:*');
    assert.equal(await page.locator('#rows details').count(),1);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#search').inputValue(),'');
    await page.locator('#view').selectOption('changes');
    await page.locator('#next').click();
    assert.equal(await page.locator('#rows details').count(),3);
    await page.locator('#kind').selectOption('changed');
    assert.equal(await page.locator('#rows details').count(),1);
    const summary=page.locator('#rows summary').first();
    await summary.focus(); await page.keyboard.press('Enter');
    assert.equal(await page.locator('#rows details[open]').count(),1);
    assert.match(await page.locator('.evidence').innerText(),/\^1\.0\.0/);
    assert.match(await page.locator('.evidence').innerText(),/\^2\.0\.0/);
    assert.match(await page.locator('.evidence').innerText(),new RegExp(report.snapshots[0].commit));
    await page.keyboard.press('Space');
    assert.equal(await page.locator('#rows details[open]').count(),0);
    await page.locator('#reset').click();
    // Global arrows operate outside controls; arrows inside search remain text navigation.
    await page.locator('h1').click();await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#snapshot').inputValue(),'2');
    await page.keyboard.press('ArrowLeft');
    assert.equal(await page.locator('#snapshot').inputValue(),'1');
    await page.keyboard.press('/');
    assert.equal(await page.locator('#search').evaluate(el=>el===document.activeElement),true);
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#snapshot').inputValue(),'1');
    await page.keyboard.press('Tab');
    assert.equal(await page.locator('#ecosystem').evaluate(el=>el===document.activeElement),true);
    await page.locator('#snapshot').selectOption('4');
    await page.locator('#kind').selectOption('unknown');
    assert.ok(await page.locator('#rows details').count()>0);
    assert.match(await page.locator('#warnings').innerText(),/malformed_manifest/);
    await page.locator('#reset').click();
    await page.locator('#snapshot').selectOption(String(report.snapshots.length-1));
    await page.locator('#view').selectOption('snapshot');
    assert.equal(await page.locator('#next').isDisabled(),true);
    assert.equal(await page.locator('#rows details').count(),100);
    await page.locator('#page-next').click();
    assert.match(await page.locator('#page-status').innerText(),/Page 2 of 3/);
    await page.locator('#page-next').click();
    assert.equal(await page.locator('#rows details').count(),6);
    await page.locator('#search').fill('globalThis');
    assert.equal(await page.locator('#rows details').count(),1);
    assert.match(await page.locator('#rows summary').innerText(),/<script>globalThis.PWNED=1<\/script>/);
    await page.locator('#rows summary').click();
    assert.match(await page.locator('.evidence').innerText(),/@@DATA@@/);
    assert.equal(await page.evaluate(() => globalThis.PWNED),undefined);
    assert.equal(await page.locator('img').count(),0);
    assert.deepEqual(attemptedNetwork,[]);
    assert.deepEqual(errors,[]);
    assert.deepEqual(consoleErrors,[]);
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth+1));
    await page.setViewportSize({width:1280,height:900});
    await page.locator('#reset').click();await page.locator('#snapshot').selectOption('1');await page.locator('#view').selectOption('changes');
    await page.locator('#rows summary').first().click();
    if(process.env.RST_SCREENSHOT)await page.screenshot({path:process.env.RST_SCREENSHOT,fullPage:true});
    console.log(JSON.stringify({status:'passed',browser:browser.version(),network:'offline context, all requests routed to abort, CSP blocks connections',external_requests:attemptedNetwork.length,page_errors:errors.length,checks:['snapshot navigation','baseline','ecosystem/category/search/change filters','before/after and commit provenance','keyboard arrows, slash, Escape, Tab, Enter, Space','coverage warnings','pagination','hostile text inert','mobile overflow','zero external requests']}));
    await context.close();
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
