'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const context = await browser.newContext({offline:true,serviceWorkers:'block',viewport:{width:1200,height:900}});
    const network=[], errors=[];
    await context.route('**/*',route=>{if(route.request().url().startsWith('file:'))return route.continue();network.push(route.request().url());return route.abort();});
    const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
    await page.goto(pathToFileURL(path.resolve(process.argv[2])).href);
    assert.equal(await page.locator('#analysis-label').isVisible(),true);
    await page.locator('#analysis').selectOption('lockfiles');
    await page.locator('#view').selectOption('snapshot');
    assert.equal(await page.locator('#rows details').count(),100);
    await page.locator('#page-next').click();assert.match(await page.locator('#page-status').innerText(),/Page 2/);
    await page.locator('#search').fill('real-package');assert.equal(await page.locator('#rows details').count(),1);
    await page.locator('#rows summary').click();assert.match(await page.locator('.evidence').innerText(),/1\.2\.3/);
    await page.keyboard.press('Escape');
    await page.locator('#search').fill('globalThis');
    await page.locator('#rows summary').focus();await page.keyboard.press('Enter');
    assert.match(await page.locator('.evidence').innerText(),/@@DATA@@/);
    assert.equal(await page.evaluate(()=>globalThis.PWNED),undefined);
    assert.equal(await page.locator('img').count(),0);
    await page.locator('#reset').click();
    await page.locator('#view').selectOption('changes');
    await page.locator('h1').click();await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#snapshot').inputValue(),'1');
    assert.equal(await page.locator('#rows details').count(),3);
    await page.locator('#kind').selectOption('changed');
    assert.equal(await page.locator('#rows details').count(),1);
    await page.locator('#rows summary').focus();await page.keyboard.press('Space');
    const evidence=await page.locator('.evidence').innerText();
    assert.match(evidence,/1\.0\.0/);assert.match(evidence,/2\.0\.0/);assert.match(evidence,/integrity, optional, version/);
    assert.match(evidence,/Blob: [0-9a-f]{40}/);
    await page.locator('#reset').click();await page.locator('#next').click();
    await page.locator('#kind').selectOption('unknown');assert.equal(await page.locator('#rows details').count(),100);
    assert.match(await page.locator('#warnings').innerText(),/unsupported_lockfile_version/);
    assert.match(await page.locator('#warnings').innerText(),/Incomplete lockfile analysis/);
    await page.locator('#analysis').selectOption('declarations');
    await page.locator('#snapshot').selectOption('1');await page.locator('#reset').click();
    assert.equal(await page.locator('#rows details').count(),1);
    await page.locator('#analysis').selectOption('lockfiles');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    assert.deepEqual(network,[]);assert.deepEqual(errors,[]);
    console.log(JSON.stringify({status:'passed',browser:browser.version(),external_requests:network.length,page_errors:errors.length,checks:['lockfile/declaration switch','snapshot/change filters','location and alias search','before/after metadata and provenance','pagination','keyboard Enter Space Escape arrows','incomplete analysis','hostile strings inert','mobile layout']}));
    await context.close();
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
